Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -16,20 +16,25 @@ jobs:
       - name: Checkout source
         uses: actions/checkout@v4
 
-      - name: Checked
+      - name: Check and build Packages
         run: |
+          # Xoá file Packages cũ nếu có
+          rm -f Packages Packages.gz
+          
+          # Lọc bỏ .deb lỗi
           for f in *.deb; do
-             echo "Checking $f ..."
-	           if ! dpkg-deb -I "$f" >/dev/null 2>&1; then
-		            echo "❌ Error in $f → removing"
-		            rm -rf "$f"
-	           else
-		           echo "✅ OK: $f"
-	           fi
+            echo "Checking $f ..."
+            if ! dpkg-deb -I "$f" >/dev/null 2>&1; then
+              echo "❌ Error in $f → removing"
+              rm -rf "$f"
+            else
+              echo "✅ OK: $f"
+            fi
           done
-        
-          touch Packages
-          dpkg-scanpackages -m . /dev/null >> Packages
+          
+          # Build Packages + Packages.gz
+          dpkg-scanpackages -m . /dev/null > Packages
+          gzip -c9 Packages > Packages.gz
 
       - name: Upload GitHub Pages artifact
         uses: actions/upload-pages-artifact@v3
